import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './styles/globals.scss';
import localFont from 'next/font/local';
import { Header } from '@/src/widgets/Header';
import { Footer } from '@/src/widgets/Footer';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const cormorant = localFont({
	src: [
		{
			path: '../public/fonts/Cormorant/Cormorant-Medium.woff2',
			weight: '500',
			style: 'normal',
		},
	],
	variable: '--cormorant',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='ru'
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
			<body className={`${cormorant.className} light_theme min-h-full flex flex-col`}>
				<Header />
				<main className='main'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
